version:                '2'
services:
    nginx-proxy:
        image:          jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    mysvgfile:
        image:          nginx
        container_name: mysvgfile
        volumes:
            - ~/somesvgtest/www:/usr/share/nginx/html
        environment:
            - VIRTUAL_HOST=mysvgfile.local

    goserve:
        build:          goservesvg
        container_name: goservesvg
        environment:
            - VIRTUAL_HOST=goservesvg.local
